-- Phase 1C fix: standalone member identity
--
-- The finalized authentication model (approved-email allowlist + this
-- application's own signed session cookie) deliberately does NOT create or use
-- Supabase Auth identities for members. See
-- docs/BACKEND-IMPLEMENTATION-PLAN.md section 2.2.
--
-- The initial schema declared:
--   id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE
-- with no DEFAULT. That made manual member seeding impossible under the
-- finalized model:
--   * an INSERT that omits `id` fails the NOT NULL constraint (no default), and
--   * an INSERT that supplies a UUID fails the foreign key, because producing a
--     matching auth.users row would mean creating a Supabase Auth user.
--
-- The smallest correction is to make `members` own its identity: drop the
-- foreign key and let the column generate its own UUID. This adds no column,
-- introduces no new table, and does not touch xp_ledger (its `user_id` FK
-- already targets members(id), which is unchanged).
--
-- No real member rows exist yet, so there is no data to migrate.

--------------------------------------------------------------------------------
-- 1. members.id becomes self-generated
--------------------------------------------------------------------------------

ALTER TABLE members
    DROP CONSTRAINT members_id_fkey;

ALTER TABLE members
    ALTER COLUMN id SET DEFAULT gen_random_uuid();

--------------------------------------------------------------------------------
-- 2. COMMENTS
--------------------------------------------------------------------------------

COMMENT ON TABLE members IS
    'Approved Coders Club members. Identity is owned by this table (no Supabase Auth dependency); membership is manually maintained and annual validity is July-June.';

COMMENT ON COLUMN members.id IS
    'Application-owned member identifier. Generated by gen_random_uuid(); not linked to Supabase Auth.';

--------------------------------------------------------------------------------
-- 3. NOTE ON PHASE 1B RLS POLICIES (intentionally unchanged)
--------------------------------------------------------------------------------
-- The `members` SELECT policy from Phase 1B is `USING (auth.uid() = id)`.
-- Phase 1C does not create Supabase Auth sessions, so auth.uid() is always NULL
-- and the policy never matches. That is the desired state: `members` is NOT
-- directly readable with the anon key. All application reads go through the
-- narrow SECURITY DEFINER functions added in
-- 20260914000001_member_login_lookup.sql.
--
-- The policies are left in place rather than dropped: they remain correct if a
-- Supabase Auth identity is introduced for any future purpose, and removing
-- them is not required for the approved-email login model.
